version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:13-alpine3.14
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - $PWD/tmp/data:/var/lib/postgresql/data/pgdata
  migrator:
    image: xavsierra/radioyerevan-pg-migrator:dev
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  publisher:
    image: xavsierra/radioyerevan-joke-publisher:dev
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      CONSOLE_PUBLISHER_ENABLED: "true"
      TWITTER_PUBLISHER_ENABLED: "false"
      CONSUMER_KEY: fake_consumer_key
      CONSUMER_SECRET: fake_consumer_secret
      ACCESS_TOKEN: fake_access_token
      ACCESS_TOKEN_SECRET: fake_access_token_secret
      PUBLISHER_CRON: "0 0/2 * ? * * *"